name: Todo App Pipeline

on:
  push:
    branches:
      - main

jobs:
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: log
        run: |
          ls -al
          node -v
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
          cache: 'npm'
          cache-dependency-path: |
            frontend/package-lock.json
      - name: log
        run: |
          ls -al
          node -v
      - name: Run test
        run: |
          cd frontend
          npm i
          npm run test
  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "Hello Backend Unit Test World"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
          cache-dependency-path: | # optional
            server/*.gradle*
            server/**/gradle-wrapper.properties
      - name: Backend Unit Test
        run: |
          docker run --rm\
            -d\
            -p 4566:4566\
            -p 4510-4559:4510-4559\
            -e DYNAMODB_SHARE_DB=1\
            -v ./init:/etc/localstack/init/ready.d\
            -i localstack/localstack
          cd server
          ./gradlew test
  build-app-image:
    runs-on: ubuntu-latest
    needs:
      - frontend-unit-test
      - backend-unit-test
    steps:
      - name: log
        run: |
          echo "frontend and backend build create image"
