name: Todo App Pipeline

on:
  push:
    branches:
      - main

jobs:
  frontend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          ls -al
          node -v
  backend-unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: log
        run: |
          echo "Hello Backend Unit Test World"
  build-app-image:
    runs-on: ubuntu-latest
    needs:
      - frontend-unit-test
      - backend-unit-test
    steps:
      - name: log
        run: |
          echo "frontend and backend build create image"
